language: julia
os:
  - linux
  - osx
julia:
  - 0.6
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --depwarn=no -e 'Pkg.add("Expokit")'
  - julia -e 'Pkg.checkout("https://github.com/ZKSI/QSWalk.jl.git", "julia-0.6", update=true); Pkg.build("QSWalk"); Pkg.test("QSWalk"; coverage=true)'
after_success:
- julia --depwarn=no -e 'cd(Pkg.dir("QSWalk")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
